# Generated by Django 4.1.3 on 2022-11-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_purchase_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='additional_info',
            field=models.TextField(),
        ),
    ]
